### ISSUE TITLE
Unable to build with OpenSSL 1.1.0e

### ISSUE THREAD

**Issue by 4e6** [peti/hopenssl#2]
System info:

```
`--[master]± openssl version 
OpenSSL 1.1.0e  16 Feb 2017
`--[master]± ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
`--[master]± cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
```

Steps to reproduce:

```
`--[master]± cabal sandbox init
Writing a default package environment file to
/home/dbushev/projects/Aviora/hopenssl/cabal.sandbox.config
Creating a new sandbox at
/home/dbushev/projects/Aviora/hopenssl/.cabal-sandbox

`--[master]± cabal configure
Resolving dependencies...
Configuring hopenssl-2...

`--[master]± cabal --require-sandbox build
Building hopenssl-2...
Preprocessing library hopenssl-2...
In file included from dist/build/OpenSSL/EVP/Digest_hsc_make.c:1:0:
Digest.hsc: In function ‘main’:
Digest.hsc:99:15: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
/usr/lib/ghc-8.0.1/template-hsc.h:86:39: note: in definition of macro ‘hsc_size’
     hsc_printf("(%ld)", (long) sizeof(t));
                                       ^
In file included from /usr/include/sched.h:29:0,
                 from /usr/include/pthread.h:23,
                 from /usr/include/openssl/crypto.h:406,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/evp.h:16,
                 from Digest.hsc:34:
/usr/lib/ghc-8.0.1/template-hsc.h:89:62: error: field ‘y__’ has incomplete type
     hsc_printf("(%ld)", (long) offsetof(struct {char x__; t (y__); }, y__));
                                                              ^
Digest.hsc:100:5: note: in expansion of macro ‘hsc_alignment’
compiling dist/build/OpenSSL/EVP/Digest_hsc_make.c failed (exit code 1)
command was: /usr/bin/gcc -c dist/build/OpenSSL/EVP/Digest_hsc_make.c -o dist/build/OpenSSL/EVP/Digest_hsc_make.o -fno-stack-protector -fno-stack-protector -D__GLASGOW_HASKELL__=800 -Dlinux_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dlinux_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/usr/lib/ghc-8.0.1/bytestring-0.10.8.1/include -I/usr/lib/ghc-8.0.1/base-4.9.0.0/include -I/usr/lib/ghc-8.0.1/integer-gmp-1.0.0.1/include -I/usr/lib/ghc-8.0.1/include -I/usr/lib/libffi-3.2.1/include -I/usr/lib/ghc-8.0.1/include/
```

**Comment by peti** [comment]
Ah, crap. OpenSSL no longer exposes this type: https://github.com/openssl/openssl/issues/3513. This means that de facto I cannot provide a Storable instance for it.

**Comment by peti** [comment]
https://hackage.haskell.org/package/hopenssl-2.1 should work properly now. Thank you for the bug report.

**Comment by 4e6** [comment]
Yes, it works now, thanks!
